services:
  # Backend FastAPI Service
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./chroma_db:/app/chroma_db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/aethernotes_db
    depends_on:
<<<<<<< HEAD
      db:
        condition: service_healthy
      ollama:
        condition: service_started
=======
      - redis
      - db:
          condition: service_healthy
  
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
>>>>>>> 22342c7 (setup redis in docker-compose)

  # PostgreSQL Database Service
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aethernotes_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aethernotes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # frontend Vite React+TS
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

volumes:
  postgres_data:
  ollama_models: 