version: '3.8'

services:
  # Backend FastAPI Service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/aethernotes_db
    depends_on:
      - db

  # PostgreSQL Database Service
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aethernotes_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: